services:
  ripx:
    image: ghcr.io/project-absolute/ripx:main
    hostname: ripx
    container_name: ripx
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data:/data
      - /usr/share/zoneinfo/Europe/Moscow:/etc/localtime:ro
    restart: unless-stopped