services:
  ripx:
    image: ghcr.io/project-absolute/ripx:dev
    hostname: ripx
    container_name: ripx
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - /usr/share/zoneinfo/Europe/Moscow:/etc/localtime:ro
    networks:
      - edge-network
    restart: unless-stopped

networks:
  edge-network:
    external: true
